project_mvc/Models/Company.cs
using System.ComponentModel.DataAnnotations;

namespace project_mvc.Models
{
    public class Company
    {
        public int Id { get; set; }
        [MinLength(3)]
        public string Name { get; set; }
        public string Description { get; set; }
        public List<Product> Products { get; set; }
    }
}

project_mvc/Areas/Admin/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;

namespace project_mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompaniesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
    }
}

project_mvc/Areas/Admin/Views/Companies/Create.cshtml
@model project_mvc.Models.Company

@section Title {
                Company
}
@section heading {
                Create
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

project_mvc/Areas/Admin/Views/Companies/Create1.cshtml
@model Company
@section Title {
            Company
}
@section heading {
            Create
}
<form asp-area="admin" asp-action="cerate" asp-controller="Companies" >

    <div class="form-group">
        <label asp-for="Name">comp name</label>
        @*<label for="exampleInputName">Name</label>*@
        <input asp-for="Name"  class="form-control" placeholder="name"/>
        <span class="text-danger" asp-validation-for="Name"></span>
        @*<input name="Name" type="text" class="form-control" id="exampleInputName" placeholder="Name">*@
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>
@*
    this using html helper
@using(@Html.BeginForm(FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(c=>c.Name)
        @Html.EditorFor(c=>c.Name,new{htmlAttributes=new{ @class="form-control"}})
        @Html.ValidationMessageFor(c=>c.Name);
    </div>
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
*@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

project_mvc/Areas/Admin/Views/Companies/Index.cshtml
@model Company
@section Title {
        Company
}
@section heading {
        show
}